# -*- coding: utf-8 -*-
"""1주차 과제(댕댕이 RPG).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--3l0M_KJNPgDFMWo-olbkGawdoNUKo5
"""

import time
import random
import os

class charecter:
    def __init__(self, name, hp, skill, power):
        self.name = name
        self.hp = hp
        self.power = power
        self.skill = skill

    def __str__(self):
        return self.name

    def attack(self, target):
        target.hp -= self.power
        target.hp = max(0, target.hp)
        return target.hp

class player(charecter):
    def __init__(self, name, hp, power):
        super().__init__(name, hp, None, power)

class monster(charecter):
    def __init__(self, name, hp, skill, power):
        super().__init__(name, hp, skill, power)

# 플레이어, 몬스터 저장
charecters = {}

# 게임 시작
def game_start():
    while True:
        print("""
            ╔═══════════════════════╗
                       선택

                    1. 게임시작
                    2. 게임종료
            ╚═══════════════════════╝
        """) # 삼중따옴표: 입력하는 문자열 구조 그대로 출력
        command = input(">> 선택하세요: ")
        if command == '1':
            os.system("cls")
            player_create()
        elif command == '2':
            print("게임을 종료합니다.")
            time.sleep(2)
            os.system("cls")
            exit()
        else:
            print("다시 선택해주세요.")
            os.system("cls")

# 캐릭터 이름 입력
def player_create():
    global char
    print("댕댕이의 이름을 입력해주세요")
    player_name = input(">> ")
    charecters[player_name] = player(player_name, 100, random.randint(15, 30))
    print(f"댕댕이의 이름은 {player_name}입니다.")
    char = charecters[player_name]
    time.sleep(2)
    os.system("cls")
    story()

# 스토리 진행
def story():
    print(f"{char.name}이(가) 어디갔지~?")
    time.sleep(2)
    print("산책하다 보니 너무 멀리까지 와버렸다 멍.. 얼른 집으로 돌아가자!")
    time.sleep(2)
    print(f"{char.name}이(가) 무사히 집에 돌아갈 수 있도록 도와주세요.")
    time.sleep(2)
    os.system("cls")
    road_scene()

def road_scene():
    print(f"{char.name}이(가) 집으로 돌아가는 중입니다.")
    time.sleep(2)
    print("""~ ૮ ･ ﻌ･ა ~""")
    time.sleep(2)
    print("...")
    time.sleep(2)
    print("...")
    time.sleep(2)
    random_scene()

# 보물상자와 전투 랜덤 선택
def random_scene():
    treasure_value = 30
    battle_value = 70

    random_value = random.random() * 100
    while True:
        if random_value <= treasure_value:
            treasure()
        else:
            battle()

# 보물상자
def treasure():
    while True:
        print("=========================================================")
        print("상자를 발견했다! 열어볼까?")
        time.sleep(1)
        print("""
            1. 연다.
            2. 열지 않는다.
            """)
        command = input(">> ")
        if command == "1":
            #보물상자 간식과 몬스터 랜덤 선택
            random.choice([treasure_snack(), treasure_monster()])
        elif command == "2":
            road_scene()
        else:
            print("다시 선택해달라멍!")

# 보물상자_간식
def treasure_snack():
    print("맛있는 간식이야! 피로가 조금 회복되는 것 같아!")
    time.sleep(2)
    if char.hp < 100:
        heal = random.randint(1, 10)
        char.hp = min(100, char.hp + heal)
    else:
        None
    print(f"{char.name}의 현제 체력은 {char.hp}입니다.")
    time.sleep(1.5)
    print("=========================================================")
    time.sleep(1.5)
    road_scene()

# 보물상자_몬스터
def treasure_monster():
    print("=========================================================")
    print("앗, 상자에서 벌이 튀어나왔다!")
    time.sleep(1.5)
    print("벌에 쏘인 것 같다 멍..")
    time.sleep(2)
    char.hp -= random.randint(1, 10)
    print(f'{char.name}의 현재 체력은 {char.hp}이다 멍!')
    print("=========================================================")
    if char.hp <= 0:
        death()
    else:
        road_scene()

# 배틀에 참가하는 몬스터
def battle():
    global monster_list
    monster_list = [
        monster("비둘기", 55, "날개짓", random.randint(5, 15)),
        monster("쥐", 45, "갉아먹기", random.randint(1, 10)),
        monster("고양이", 40, "하악질", random.randint(10, 20)),
        monster("참새", 30, "쪼기", random.randint(10, 20)),
        monster("뱀", 35, "똬리틀기", random.randint(10, 20)),
    ]

    # 몬스터 랜덤으로 뽑기
    enemy = random.choice(monster_list)
    return monster_atk(enemy, char)

# 몬스터 공격 턴
def monster_atk(monster, player, first_attack=True):
    # 첫 번째 싸움에만 출력
    if first_attack:
        print("=========================================================")
        print(f"앗! 야생의 {monster.name}이(가) 나타났다멍!")
        time.sleep(1.5)
        while True:
            print("""
                ╔═══════════════════════╗
                        선택

                        1. 싸운다
                        2. 도망간다
                ╚═══════════════════════╝
            """)
            command = input(">> 선택하세요: ")
            if command == '1':
                break
            else:
                command == '2'
                time.sleep(1.5)
                print("도망가야겠다 멍!!")
                time.sleep(1.5)
                print("=========================================================")
                time.sleep(1.5)
                os.system("cls")
                road_scene()
                break

    monster.attack(player)

    print("=========================================================")
    time.sleep(1.5)
    print(f"{monster.name}이(가) {monster.skill}을(를) 사용했다!")
    time.sleep(1.5)
    print(f"{monster.power}의 상처를 입었다 멍...")
    time.sleep(1.5)
    print(f"현재 {char.name}의 체력은 {char.hp}이다 멍!")
    time.sleep(1.5)
    print("=========================================================")
    time.sleep(1.5)
    if char.hp <= 0:
        death()
    else:
        player_atk(monster, player, first_attack=False)

# 플레이어 공격 턴
def player_atk(monster, player, first_attack=True):
    player.attack(monster)
    print(f"{char.name}이(가) {char.power}의 상처를 입혔다!")
    time.sleep(1.5)
    print(f"현재 {monster.name}의 체력은 {monster.hp}이다 멍!")
    time.sleep(1.5)
    while True:
        if monster.hp <= 0:
            print(f"{monster.name}을(를) 물리치는데 성공했다 멍!")
            time.sleep(1.5)
            print("=========================================================")
            time.sleep(1.5)
            os.system("cls")
            # 몬스터 물리칠 때마다 해당 몬스터 리스트에서 삭제
            monster_list.remove(monster)
            # 몬스터 리스트가 0이 되면 엔딩
            if len(monster_list) <= 0:
                print("""        ╱◥▦◣
                        ,,, ,,, │田│田│ ,,, ,,,
                        """)
                time.sleep(1)
                print("앗, 저기 우리 집이 보인다! 무사히 데려다줘서 고맙다 멍!")
                time.sleep(2)
                os.system("cls")
                game_start()
            else:
                road_scene()
            break
        else:
            monster_atk(monster, player, first_attack=False)
            break

# 플레이어 사망
def death():
    print(f"{char.name}이(가) 쓰러졌습니다.")
    time.sleep(2)
    os.system("cls")
    time.sleep(2)
    game_start()

game_start()
